import logging
import time
import httpx
from abc import ABC, abstractmethod
from enum import Enum
from typing import Any, Optional

from app.core.config import settings
from app.utils.id import generate_uuid
from pydantic import BaseModel, Field

logger = logging.getLogger("kisan_mitra_ai.telephony")


class CallStatus(str, Enum):
    """Lifecycle status codes for telephone calls."""
    RINGING = "ringing"
    ANSWERED = "answered"
    BUSY = "busy"
    COMPLETED = "completed"
    FAILED = "failed"
    DROPPED = "dropped"
    TRANSFERRED = "transferred"


class CallDirection(str, Enum):
    """Direction of the call."""
    INBOUND = "inbound"
    OUTBOUND = "outbound"


class TelephonyStatus(str, Enum):
    """Operational status of telephony adapters."""
    ACTIVE = "active"
    INACTIVE = "inactive"
    DEGRADED = "degraded"
    MAINTENANCE = "maintenance"


class CallMetadata(BaseModel):
    """
    Standard metadata describing a telephone call session.
    """
    caller: str = Field(..., description="Caller identification phone number/SIP URI.")
    callee: str = Field(..., description="Callee identification phone number/SIP URI.")
    call_direction: CallDirection = Field(..., description="Call direction indicator.")
    recording_url: Optional[str] = Field(default=None, description="URL of call recording audio.")
    duration_seconds: float = Field(default=0.0, description="Duration of the call session.")
    custom_metadata: dict[str, Any] = Field(default_factory=dict, description="Extensible configuration properties.")


class CallInput(BaseModel):
    """
    Input structure representing telephone call events.
    """
    call_id: str = Field(default_factory=generate_uuid, description="Unique call identifier.")
    status: CallStatus = Field(default=CallStatus.RINGING, description="Current call lifecycle status.")
    metadata: CallMetadata = Field(..., description="Associated call parameters.")


class CallResult(BaseModel):
    """
    Result response output generated by telephony operations.
    """
    call_id: str = Field(..., description="Reference call identifier.")
    success: bool = Field(..., description="Indicates if operation succeeded.")
    response_text: str = Field(..., description="TTS text or prompt played to call party.")
    error: Optional[str] = Field(default=None, description="Error details if execution failed.")


class ITelephonyProvider(ABC):
    """
    Abstract interface defining capabilities that all telephony providers must implement.
    """
    @property
    @abstractmethod
    def id(self) -> str:
        pass

    @property
    @abstractmethod
    def version(self) -> str:
        pass

    @property
    @abstractmethod
    def capabilities(self) -> list[str]:
        pass

    @property
    @abstractmethod
    def status(self) -> TelephonyStatus:
        pass

    @property
    @abstractmethod
    def latency_ms(self) -> float:
        pass

    @property
    @abstractmethod
    def metadata(self) -> dict[str, Any]:
        pass

    @abstractmethod
    async def initiate_call(self, callee: str, caller: str) -> str:
        """Starts an outbound call, returning the call ID."""
        pass

    @abstractmethod
    async def hangup(self, call_id: str) -> bool:
        """Terminates an active call."""
        pass

    @abstractmethod
    async def get_call_details(self, call_id: str) -> Optional[CallInput]:
        """Queries metadata for a specific call."""
        pass

    @abstractmethod
    async def send_dtmf(self, call_id: str, digits: str) -> bool:
        """Sends keypress digits to an active call."""
        pass

    @abstractmethod
    async def play_audio(self, call_id: str, audio_url: str) -> bool:
        """Plays an audio URL file into the call stream."""
        pass

    @abstractmethod
    async def speak_text(self, call_id: str, text: str, language: str) -> bool:
        """Speaks text content via Text-to-Speech (TTS)."""
        pass

    @abstractmethod
    async def start_recording(self, call_id: str) -> bool:
        """Starts recording call audio."""
        pass

    @abstractmethod
    async def stop_recording(self, call_id: str) -> Optional[str]:
        """Stops recording and returns recording audio URL."""
        pass

    @abstractmethod
    async def health_check(self) -> bool:
        """Queries provider health."""
        pass


class BaseTelephonyProvider(ITelephonyProvider):
    """
    Base class implementing shared attributes and boilerplate code for telephony providers.
    """
    def __init__(
        self,
        provider_id: str,
        version: str = "1.0.0",
        capabilities: Optional[list[str]] = None
    ) -> None:
        self._id = provider_id
        self._version = version
        self._capabilities = capabilities or []
        self._status = TelephonyStatus.ACTIVE
        self._latency_ms = 0.0
        self._metadata: dict[str, Any] = {}
        self._active_calls: dict[str, CallInput] = {}

    @property
    def id(self) -> str:
        return self._id

    @property
    def version(self) -> str:
        return self._version

    @property
    def capabilities(self) -> list[str]:
        return self._capabilities

    @property
    def status(self) -> TelephonyStatus:
        return self._status

    @status.setter
    def status(self, val: TelephonyStatus) -> None:
        self._status = val

    @property
    def latency_ms(self) -> float:
        return self._latency_ms

    @latency_ms.setter
    def latency_ms(self, val: float) -> None:
        self._latency_ms = val

    @property
    def metadata(self) -> dict[str, Any]:
        return self._metadata

    async def initiate_call(self, callee: str, caller: str) -> str:
        start_time = time.perf_counter()
        call_id = f"CALL-OUT-{generate_uuid()[:8]}"
        meta = CallMetadata(
            caller=caller,
            callee=callee,
            call_direction=CallDirection.OUTBOUND
        )
        self._active_calls[call_id] = CallInput(call_id=call_id, status=CallStatus.ANSWERED, metadata=meta)
        self.latency_ms = round((time.perf_counter() - start_time) * 1000, 4)
        logger.info(f"[{self.id}] Initiated outbound call '{call_id}' to {callee}")
        return call_id

    async def hangup(self, call_id: str) -> bool:
        if call_id in self._active_calls:
            self._active_calls[call_id].status = CallStatus.COMPLETED
            logger.info(f"[{self.id}] Call hung up: '{call_id}'")
            return True
        return False

    async def get_call_details(self, call_id: str) -> Optional[CallInput]:
        return self._active_calls.get(call_id)

    async def send_dtmf(self, call_id: str, digits: str) -> bool:
        logger.info(f"[{self.id}] Call '{call_id}' received DTMF: {digits}")
        return True

    async def play_audio(self, call_id: str, audio_url: str) -> bool:
        logger.info(f"[{self.id}] Call '{call_id}' playing audio: {audio_url}")
        return True

    async def speak_text(self, call_id: str, text: str, language: str) -> bool:
        logger.info(f"[{self.id}] Call '{call_id}' speaking text ({language}): {text}")
        return True

    async def start_recording(self, call_id: str) -> bool:
        logger.info(f"[{self.id}] Started recording call '{call_id}'")
        return True

    async def stop_recording(self, call_id: str) -> Optional[str]:
        logger.info(f"[{self.id}] Stopped recording call '{call_id}'")
        return f"http://telephony-storage.local/{call_id}.wav"

    async def health_check(self) -> bool:
        return self._status == TelephonyStatus.ACTIVE


class TwilioTelephonyProvider(BaseTelephonyProvider):
    """Twilio outbound voice dialer production client."""
    async def initiate_call(self, callee: str, caller: str) -> str:
        sid = settings.TWILIO_ACCOUNT_SID
        token = settings.TWILIO_AUTH_TOKEN
        if sid and token:
            try:
                start_time = time.perf_counter()
                async with httpx.AsyncClient(timeout=4.0) as client:
                    response = await client.post(
                        f"https://api.twilio.com/2010-04-01/Accounts/{sid}/Calls.json",
                        auth=(sid, token),
                        data={
                            "To": callee,
                            "From": caller or settings.TWILIO_PHONE_NUMBER or "+1234567890",
                            "Url": "https://handler.twilio.com/twiml/EH..."
                        }
                    )
                    self.latency_ms = round((time.perf_counter() - start_time) * 1000, 4)
                    if response.status_code in (200, 201):
                        data = response.json()
                        call_id = data.get("sid", f"TW-{generate_uuid()[:8]}")
                        meta = CallMetadata(caller=caller, callee=callee, call_direction=CallDirection.OUTBOUND)
                        self._active_calls[call_id] = CallInput(call_id=call_id, status=CallStatus.RINGING, metadata=meta)
                        logger.info(f"[TwilioTelephonyProvider] Call successfully initiated: {call_id}")
                        return call_id
            except Exception as e:
                logger.warning(f"[TwilioTelephonyProvider] HTTP voice dial failed, using mock: {e}")
        return await super().initiate_call(callee, caller)

    async def health_check(self) -> bool:
        if not settings.TWILIO_ACCOUNT_SID and not settings.TWILIO_AUTH_TOKEN:
            return self.status == TelephonyStatus.ACTIVE
        return bool(settings.TWILIO_ACCOUNT_SID and settings.TWILIO_AUTH_TOKEN)


class PlivoTelephonyProvider(BaseTelephonyProvider):
    """Plivo outbound voice dialer production client."""
    async def initiate_call(self, callee: str, caller: str) -> str:
        auth_id = settings.PLIVO_AUTH_ID
        auth_token = settings.PLIVO_AUTH_TOKEN
        if auth_id and auth_token:
            try:
                start_time = time.perf_counter()
                async with httpx.AsyncClient(timeout=4.0) as client:
                    response = await client.post(
                        f"https://api.plivo.com/v1/Account/{auth_id}/Call/",
                        auth=(auth_id, auth_token),
                        json={
                            "to": callee,
                            "from": caller or settings.PLIVO_PHONE_NUMBER or "+1234567890",
                            "answer_url": "https://answer.plivo.local"
                        }
                    )
                    self.latency_ms = round((time.perf_counter() - start_time) * 1000, 4)
                    if response.status_code in (200, 201, 202):
                        data = response.json()
                        call_id = data.get("request_uuid", f"PL-{generate_uuid()[:8]}")
                        meta = CallMetadata(caller=caller, callee=callee, call_direction=CallDirection.OUTBOUND)
                        self._active_calls[call_id] = CallInput(call_id=call_id, status=CallStatus.RINGING, metadata=meta)
                        logger.info(f"[PlivoTelephonyProvider] Call successfully initiated: {call_id}")
                        return call_id
            except Exception as e:
                logger.warning(f"[PlivoTelephonyProvider] HTTP voice dial failed: {e}")
        return await super().initiate_call(callee, caller)

    async def health_check(self) -> bool:
        if not settings.PLIVO_AUTH_ID and not settings.PLIVO_AUTH_TOKEN:
            return self.status == TelephonyStatus.ACTIVE
        return bool(settings.PLIVO_AUTH_ID and settings.PLIVO_AUTH_TOKEN)


class ExotelTelephonyProvider(BaseTelephonyProvider):
    """Exotel outbound voice dialer production client."""
    async def initiate_call(self, callee: str, caller: str) -> str:
        sid = settings.TWILIO_ACCOUNT_SID
        token = settings.TWILIO_AUTH_TOKEN
        if sid and token:
            try:
                start_time = time.perf_counter()
                async with httpx.AsyncClient(timeout=4.0) as client:
                    response = await client.post(
                        f"https://api.exotel.com/v1/Accounts/{sid}/Calls/connect.json",
                        auth=(sid, token),
                        data={
                            "From": caller,
                            "To": callee,
                            "CallerId": sid
                        }
                    )
                    self.latency_ms = round((time.perf_counter() - start_time) * 1000, 4)
                    if response.status_code in (200, 201):
                        data = response.json()
                        call_sid = data.get("Call", {}).get("Sid", f"EX-{generate_uuid()[:8]}")
                        meta = CallMetadata(caller=caller, callee=callee, call_direction=CallDirection.OUTBOUND)
                        self._active_calls[call_sid] = CallInput(call_id=call_sid, status=CallStatus.RINGING, metadata=meta)
                        logger.info(f"[ExotelTelephonyProvider] Connect initiated: {call_sid}")
                        return call_sid
            except Exception as e:
                logger.warning(f"[ExotelTelephonyProvider] HTTP call failed: {e}")
        return await super().initiate_call(callee, caller)


class BSNLTelephonyProvider(BaseTelephonyProvider):
    """BSNL SIP gateway adapter production client."""
    async def initiate_call(self, callee: str, caller: str) -> str:
        return await super().initiate_call(callee, caller)


class TelephonyProviderRegistry:
    """
    Registry supervising loading, versioning, health, and registry tracking of telephony providers.
    """
    def __init__(self, event_bus: Optional[Any] = None, governance_engine: Optional[Any] = None) -> None:
        self._providers: dict[str, ITelephonyProvider] = {}
        self._event_bus = event_bus
        self._governance_engine = governance_engine

    def register(self, provider: ITelephonyProvider) -> None:
        """Registers a telephony provider into the MIP."""
        self._providers[provider.id] = provider
        logger.info(f"Registered Telephony Provider '{provider.id}' v{provider.version}.")

        # Auto-register with Governance Engine if present
        if self._governance_engine:
            try:
                self._governance_engine.register_artifact(
                    artifact_type="telephony_provider",
                    artifact_id=provider.id,
                    version=provider.version,
                    status=provider.status.value
                )
            except Exception as e:
                logger.error(f"Failed to register provider '{provider.id}' in governance ledger: {e}")

    def deregister(self, provider_id: str) -> None:
        """Deregisters a telephony provider."""
        if provider_id in self._providers:
            del self._providers[provider_id]
            logger.info(f"Deregistered Telephony Provider '{provider_id}'.")

    def discover(self, provider_id: str) -> Optional[ITelephonyProvider]:
        """Looks up a telephony provider by ID."""
        return self._providers.get(provider_id)

    def list_providers(self) -> list[ITelephonyProvider]:
        """Lists all registered telephony providers."""
        return list(self._providers.values())

    def validate_dependencies(self, provider_id: str) -> bool:
        """Validates that a telephony provider has its configured properties."""
        provider = self.discover(provider_id)
        if not provider:
            return False
        if not provider.id or not provider.version or not provider.status:
            return False
        return True

    def load_from_config(self, configs: list[dict[str, Any]]) -> None:
        """Dynamically instantiates and registers mock providers from a configuration array."""
        for cfg in configs:
            try:
                pid = cfg.get("provider_id")
                ptype = cfg.get("provider_type")
                version = cfg.get("version", "1.0.0")
                caps = cfg.get("capabilities", [])

                if not pid or not ptype:
                    continue

                provider: ITelephonyProvider

                if ptype == "twilio":
                    provider = TwilioTelephonyProvider(pid, version, caps)
                elif ptype == "plivo":
                    provider = PlivoTelephonyProvider(pid, version, caps)
                elif ptype == "exotel":
                    provider = ExotelTelephonyProvider(pid, version, caps)
                elif ptype == "bsnl":
                    provider = BSNLTelephonyProvider(pid, version, caps)
                else:
                    provider = BaseTelephonyProvider(pid, version, caps)

                self.register(provider)
            except Exception as e:
                logger.error(f"Failed to load telephony provider from configuration {cfg}: {e}")

    async def health_check(self) -> dict[str, Any]:
        """Queries health check across all registered providers."""
        report: dict[str, Any] = {}
        for pid, provider in self._providers.items():
            try:
                is_healthy = await provider.health_check()
                report[pid] = {
                    "version": provider.version,
                    "status": provider.status.value,
                    "healthy": is_healthy,
                    "latency_ms": provider.latency_ms
                }
            except Exception as e:
                report[pid] = {"healthy": False, "error": str(e)}
        return report
