from abc import ABC, abstractmethod
from collections.abc import Generator
from typing import Any

from pydantic import BaseModel, Field


class NormalizedAIResponse(BaseModel):
    """
    Standardized result structure returned by all underlying model adapters.
    """
    content: str = Field(..., description="Main output text response generated by the model.")
    model_name: str = Field(..., description="The exact ID of the model that generated this response.")
    provider_name: str = Field(..., description="The provider name (e.g. gemini, openai, ollama).")
    prompt_tokens: int = Field(default=0, description="Count of prompt tokens processed.")
    completion_tokens: int = Field(default=0, description="Count of completion tokens generated.")
    cost: float = Field(default=0.0, description="Estimated monetary cost in USD of this query execution.")
    latency_ms: float = Field(default=0.0, description="Overall request execution response latency in milliseconds.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Provider-specific execution details.")

class AIPlatformException(Exception):
    """
    Base exception class representing failures inside the AI Model Platform layer.
    """
    def __init__(self, message: str, details: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.message = message
        self.details = details or {}

class AICostLimitExceeded(AIPlatformException):
    """
    Exception thrown if executing the prompt exceeds current daily or session budget bounds.
    """
    pass

class IProviderAdapter(ABC):
    """
    Abstract Interface that all AI model adapters must implement.
    """
    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_instruction: str | None = None,
        temperature: float | None = None
    ) -> NormalizedAIResponse:
        """
        Generate a text response returning normalized execution details.
        """
        pass

    @abstractmethod
    def generate_stream(
        self,
        prompt: str,
        system_instruction: str | None = None,
        temperature: float | None = None
    ) -> Generator[str, None, None]:
        """
        Stream a text response from the model.
        """
        pass
