from typing import Any

from pydantic import BaseModel, Field


class StandardResponse(BaseModel):
    """
    Standard top-level envelope for successful API operations.
    """
    status: str = Field(default="success", description="Status code flag ('success').")
    data: Any | None = Field(None, description="Data payload containing the query output.")
    execution_time_ms: float | None = Field(None, description="Request execution duration metric.")

class ErrorResponse(BaseModel):
    """
    Standard error envelope returned on validation or backend failure.
    """
    error_code: str = Field(..., description="Machine-readable unique error tag.")
    message: str = Field(..., description="Human-readable description of what went wrong.")
    details: dict[str, Any] = Field(default_factory=dict, description="Metadata dictionary for additional details.")

class HealthResponse(BaseModel):
    """
    System status checker details.
    """
    status: str = Field(..., description="Overall platform status ('healthy' or 'degraded').")
    service: str = Field(..., description="System application name.")
    components: dict[str, str] = Field(..., description="Status checks on downstream services (DB, Redis, Chroma).")

class AgentResponse(BaseModel):
    """
    Legacy response structure returned by any Agent node after run completion.
    """
    agent_name: str = Field(..., description="The name of the agent that produced the output.")
    content: str = Field(..., description="Main output response text or recommendation string.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Execution metrics.")
    status: str = Field(default="success", description="Agent response status.")

class AgentResult(BaseModel):
    """
    Standardized payload returned by all agents in Step 4.
    """
    agent_name: str = Field(..., description="Target name of the executing agent.")
    status: str = Field(default="success", description="Execution result status ('success', 'failed', 'invalid').")
    content: str = Field(..., description="Advisory text content or serialized structured payload.")
    confidence: float = Field(default=1.0, description="Evaluation score indicating advisory confidence.")
    metrics: dict[str, Any] = Field(default_factory=dict, description="Execution metrics (latencies, token tallies).")
    logs: list[str] = Field(default_factory=list, description="Execution details log lines for telemetry tracing.")
    evidence: list[dict[str, Any]] = Field(default_factory=list, description="Structured evidence records returned by the agent.")

class UnifiedResponse(BaseModel):
    """
    Compiled response returned by the VerifierAgent.
    """
    session_id: str = Field(..., description="Session identifier.")
    trace_id: str = Field(..., description="Trace identifier.")
    final_advisory: str = Field(..., description="The consolidated vernacular advisory response text.")
    sources: list[str] = Field(default_factory=list, description="Citations and manual links consulted.")
    metrics_summary: dict[str, Any] = Field(default_factory=dict, description="Aggregated run cost and latency stats.")

class TrustedRecommendation(BaseModel):
    """
    Consolidated safety-vetted advisory generated by the DecisionEngine.
    """
    summary: str = Field(..., description="Abstract summary of the matching advice.")
    recommendation: str = Field(..., description="Direct operational guidance for the farmer.")
    evidence: list[dict[str, Any]] = Field(default_factory=list, description="Raw evidence logs collected.")
    confidence: float = Field(..., description="Calculated overall confidence rating.")
    risk: float = Field(..., description="Calculated overall safety risk score.")
    reasoning: list[str] = Field(default_factory=list, description="Trace logs detailing the reasoning steps.")
    sources: list[str] = Field(default_factory=list, description="List of source APIs or manuals consulted.")
    warnings: list[str] = Field(default_factory=list, description="Conflict alerts or safety warning flags.")
    missing_information: list[str] = Field(default_factory=list, description="Gaps in the inputs required.")
    follow_up_required: list[str] = Field(default_factory=list, description="Action items the farmer or system needs to execute.")
    safety_assessment: dict[str, Any] = Field(default_factory=dict, description="Assessment details from the Safety Guard.")
    reasoning_graph_ref: str = Field(..., description="Reference ID to the reasoning graph trace.")
