/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as VoiceCallsRouteImport } from './routes/voice-calls'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as SoilRouteImport } from './routes/soil'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as MarketRouteImport } from './routes/market'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GisMapRouteImport } from './routes/gis-map'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiPlatformRouteImport } from './routes/ai-platform'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as IndexRouteImport } from './routes/index'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceCallsRoute = VoiceCallsRouteImport.update({
  id: '/voice-calls',
  path: '/voice-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilRoute = SoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GisMapRoute = GisMapRouteImport.update({
  id: '/gis-map',
  path: '/gis-map',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlatformRoute = AiPlatformRouteImport.update({
  id: '/ai-platform',
  path: '/ai-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-platform': typeof AiPlatformRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/conversations': typeof ConversationsRoute
  '/crops': typeof CropsRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/equipment': typeof EquipmentRoute
  '/farmers': typeof FarmersRoute
  '/gis-map': typeof GisMapRoute
  '/governance': typeof GovernanceRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/market': typeof MarketRoute
  '/mission-control': typeof MissionControlRoute
  '/reports': typeof ReportsRoute
  '/satellite': typeof SatelliteRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/soil': typeof SoilRoute
  '/telemetry': typeof TelemetryRoute
  '/voice-calls': typeof VoiceCallsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-platform': typeof AiPlatformRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/conversations': typeof ConversationsRoute
  '/crops': typeof CropsRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/equipment': typeof EquipmentRoute
  '/farmers': typeof FarmersRoute
  '/gis-map': typeof GisMapRoute
  '/governance': typeof GovernanceRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/market': typeof MarketRoute
  '/mission-control': typeof MissionControlRoute
  '/reports': typeof ReportsRoute
  '/satellite': typeof SatelliteRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/soil': typeof SoilRoute
  '/telemetry': typeof TelemetryRoute
  '/voice-calls': typeof VoiceCallsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-platform': typeof AiPlatformRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/conversations': typeof ConversationsRoute
  '/crops': typeof CropsRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/equipment': typeof EquipmentRoute
  '/farmers': typeof FarmersRoute
  '/gis-map': typeof GisMapRoute
  '/governance': typeof GovernanceRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/market': typeof MarketRoute
  '/mission-control': typeof MissionControlRoute
  '/reports': typeof ReportsRoute
  '/satellite': typeof SatelliteRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/soil': typeof SoilRoute
  '/telemetry': typeof TelemetryRoute
  '/voice-calls': typeof VoiceCallsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents'
    | '/ai-platform'
    | '/alerts'
    | '/analytics'
    | '/conversations'
    | '/crops'
    | '/disease-detection'
    | '/equipment'
    | '/farmers'
    | '/gis-map'
    | '/governance'
    | '/integrations'
    | '/knowledge'
    | '/market'
    | '/mission-control'
    | '/reports'
    | '/satellite'
    | '/schemes'
    | '/settings'
    | '/sms'
    | '/soil'
    | '/telemetry'
    | '/voice-calls'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents'
    | '/ai-platform'
    | '/alerts'
    | '/analytics'
    | '/conversations'
    | '/crops'
    | '/disease-detection'
    | '/equipment'
    | '/farmers'
    | '/gis-map'
    | '/governance'
    | '/integrations'
    | '/knowledge'
    | '/market'
    | '/mission-control'
    | '/reports'
    | '/satellite'
    | '/schemes'
    | '/settings'
    | '/sms'
    | '/soil'
    | '/telemetry'
    | '/voice-calls'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/ai-agents'
    | '/ai-platform'
    | '/alerts'
    | '/analytics'
    | '/conversations'
    | '/crops'
    | '/disease-detection'
    | '/equipment'
    | '/farmers'
    | '/gis-map'
    | '/governance'
    | '/integrations'
    | '/knowledge'
    | '/market'
    | '/mission-control'
    | '/reports'
    | '/satellite'
    | '/schemes'
    | '/settings'
    | '/sms'
    | '/soil'
    | '/telemetry'
    | '/voice-calls'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentsRoute: typeof AiAgentsRoute
  AiPlatformRoute: typeof AiPlatformRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConversationsRoute: typeof ConversationsRoute
  CropsRoute: typeof CropsRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
  EquipmentRoute: typeof EquipmentRoute
  FarmersRoute: typeof FarmersRoute
  GisMapRoute: typeof GisMapRoute
  GovernanceRoute: typeof GovernanceRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MarketRoute: typeof MarketRoute
  MissionControlRoute: typeof MissionControlRoute
  ReportsRoute: typeof ReportsRoute
  SatelliteRoute: typeof SatelliteRoute
  SchemesRoute: typeof SchemesRoute
  SettingsRoute: typeof SettingsRoute
  SmsRoute: typeof SmsRoute
  SoilRoute: typeof SoilRoute
  TelemetryRoute: typeof TelemetryRoute
  VoiceCallsRoute: typeof VoiceCallsRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-calls': {
      id: '/voice-calls'
      path: '/voice-calls'
      fullPath: '/voice-calls'
      preLoaderRoute: typeof VoiceCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil': {
      id: '/soil'
      path: '/soil'
      fullPath: '/soil'
      preLoaderRoute: typeof SoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-map': {
      id: '/gis-map'
      path: '/gis-map'
      fullPath: '/gis-map'
      preLoaderRoute: typeof GisMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-platform': {
      id: '/ai-platform'
      path: '/ai-platform'
      fullPath: '/ai-platform'
      preLoaderRoute: typeof AiPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentsRoute: AiAgentsRoute,
  AiPlatformRoute: AiPlatformRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConversationsRoute: ConversationsRoute,
  CropsRoute: CropsRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
  EquipmentRoute: EquipmentRoute,
  FarmersRoute: FarmersRoute,
  GisMapRoute: GisMapRoute,
  GovernanceRoute: GovernanceRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  MarketRoute: MarketRoute,
  MissionControlRoute: MissionControlRoute,
  ReportsRoute: ReportsRoute,
  SatelliteRoute: SatelliteRoute,
  SchemesRoute: SchemesRoute,
  SettingsRoute: SettingsRoute,
  SmsRoute: SmsRoute,
  SoilRoute: SoilRoute,
  TelemetryRoute: TelemetryRoute,
  VoiceCallsRoute: VoiceCallsRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
